import { NextResponse } from 'next/server';
import { Resend } from 'resend';

export async function POST(request) {
  try {
    if (!process.env.RESEND_API_KEY) {
      console.warn('RESEND_API_KEY is not set. Cannot send feedback email.');
      return NextResponse.json({ success: true, warning: 'Email not sent (missing API key)' });
    }

    const resend = new Resend(process.env.RESEND_API_KEY);
    const body = await request.json();
    const { type, subject, message, userEmail, userName } = body;

    if (!subject || !message) {
      return NextResponse.json({ error: 'Subject and message are required' }, { status: 400 });
    }

    const htmlContent = `
      <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #E8EDEB; border-radius: 12px; overflow: hidden; background-color: #FFFFFF;">
        <div style="background-color: #1D6E72; padding: 30px 40px; text-align: center;">
          <h1 style="color: #FFFFFF; margin: 0; font-size: 24px; font-weight: 700;">New Feedback Received</h1>
        </div>
        <div style="padding: 40px; background-color: #F2F0EA;">
          <div style="background-color: #FFFFFF; padding: 20px; border-radius: 8px; border: 1px solid #E8EDEB; margin-bottom: 20px;">
            <p style="margin: 0 0 12px; font-size: 16px; color: #5A7A72;">
              <strong style="color: #1A3C34;">From:</strong> ${userName || 'Anonymous User'} ${userEmail ? `(${userEmail})` : ''}
            </p>
            <p style="margin: 0 0 12px; font-size: 16px; color: #5A7A72;">
              <strong style="color: #1A3C34;">Type:</strong> 
              <span style="display: inline-block; background-color: #C49A4A; color: #FFFFFF; padding: 4px 10px; border-radius: 12px; font-size: 14px; font-weight: 600; margin-left: 8px;">
                ${type || 'General'}
              </span>
            </p>
            <p style="margin: 0; font-size: 16px; color: #5A7A72;">
              <strong style="color: #1A3C34;">Subject:</strong> ${subject}
            </p>
          </div>
          
          <h2 style="margin: 0 0 15px; font-size: 20px; color: #1A3C34; font-weight: 600;">Message</h2>
          <div style="background-color: #FFFFFF; padding: 24px; border-radius: 8px; border-left: 4px solid #1D6E72; color: #5A7A72; white-space: pre-wrap; line-height: 1.6; font-size: 16px;">
            ${message}
          </div>
        </div>
        <div style="background-color: #FBF0DC; padding: 20px 40px; text-align: center; border-top: 1px solid #E8EDEB;">
          <p style="margin: 0; font-size: 12px; color: #5A7A72;">This email was automatically generated by the Takween Feedback System.</p>
        </div>
      </div>
    `;

    const { data, error } = await resend.emails.send({
      from: 'onboarding@resend.dev',
      to: 'takween.noreply@gmail.com',
      subject: `[Takween ${type || 'Feedback'}] ${subject}`,
      html: htmlContent
    });

    if (error) {
      console.error('Resend API error:', error);
      return NextResponse.json({ error: error.message }, { status: 400 });
    }

    return NextResponse.json({ success: true, data });

  } catch (error) {
    console.error('Feedback email error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
